Implement Wrapping Up section
hjgonzalez06/reactjs-tictactoe pull request #4
Opened 2020-12-11 05:05 UTC by hjgonzalez06

1. Display the location for each move in the format (col, row) in the move history list.
2. Bold the currently selected item in the move list.
3. Rewrite Board to use two loops to make the squares instead of hardcoding them.
4. Add a toggle button that lets you sort the moves in either ascending or descending order.
5. When someone wins, highlight the three squares that caused the win.
6. When no one wins, display a message about the result being a draw.

2020-12-11 23:33 UTC, hjgonzalez06 commented
A `git rebase` command was executed to clean up the commits history on `develop` and `work-on-wrapping-up` branches.

2020-12-14 11:47 UTC, roke77 requested changes

2020-12-14 11:47 UTC, roke77 commented on src/components/Board/index.js
> +    const determineWinnerSquare = (i, winnerLine) => {
Functions that return a boolean value are usually named with an `is` prefix, like asking a question: `isWinnerSquare?` would be a better name for it (without the ? of course)

2020-12-14 11:47 UTC, roke77 commented on src/utils/showGameStatus.js
> +           full ? `There's a DRAW` : `Next player: ${getNextPlayer(xIsNext)}`;
Do not abuse the shorthand IF statements if you have to nest conditionals. Just use a common IF/ELSE statement in that case, or even better, write `guards` like in functional programming style:

```suggestion
    if (winner) return `Winner: ${getCurrentPlayer(xIsNext)}`
    if (!winner && full) return `There's a DRAW`
    
    return `Next player: ${getNextPlayer(xIsNext)}`
```

2020-12-16 12:22 UTC, roke77 approved these changes

2020-12-16 12:23 UTC, merged